Repository JuliaData/YAML.jl, pull requests merged in 2020-12, with the labels that each got.

#91 Quote and escape strings with repr
  src/writer.jl
  test/runtests.jl
Labels: bug

#93 Bump version to 0.4.3
  Project.toml
Labels: Release

#95 Print multiline strings
  .gitignore
  Project.toml
  src/writer.jl
  test/runtests.jl
Labels: enhancement

#67 Remove outdated badges
  README.md
Labels: bug

#104 Multi constructor
  src/YAML.jl
  src/constructor.jl
  test/invalid-tag.data
  test/multi-constructor.data
  test/multi-constructor.expected
  test/runtests.jl
Labels: Tests / CI, enhancement

#105 Version bump
  Project.toml
Labels: Release
