Repository JuliaData/YAML.jl, pull requests merged in 2024-06, with the labels that each got.

#150 Issue warnings when unknown directives are loaded
  src/scanner.jl
  test/runtests.jl
Labels: enhancement

#210 Fix the bug where `prefix` buffers too much
  src/buffered_input.jl
Labels: bug

#183 [Bug Fix] Refactoring of `Mark` and `Span`, and bug fix
  src/YAML.jl
  src/mark.jl
  src/parser.jl
  src/span.jl
  src/tokens.jl
Labels: internal

#233 Throw an exception instead of a character
  src/scanner.jl
  test/runtests.jl
Labels: enhancement, Tests / CI
